apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: neo4j
  name: neo4j
spec:
  containers:
  - image: neo4j
    name: neo4j
    ports:
    - containerPort: 7474
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
