# docker compose up 
# docker compose down --rmi all
services:
  app:
    # image: python:3-slim
    build:
      context: .
      dockerfile: Dockerfile
    command: "sleep 1000000000"
    ports: 
    - 8000:8000
